apiVersion: v1
kind: Secret
metadata:
  name: cap-secret
  namespace: cap-ns
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb-svc:27017/AFF-Docker"
  PORT: "3015"
  SESSION_SECRET: "your-secret-key"